<a href="https://colab.research.google.com/github/dhonjudon/python-5CS037/blob/main/Worksheet1_TusharDhonju.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
import time

---
# PROBLEM 1: ARRAY CREATION

## Task 1.1: Empty array (2×2)

In [35]:
empty_array = np.empty((2, 2))
print("Empty Array:")
print(empty_array)

Empty Array:
[[23. 51.]
 [13. 29.]]


## Task 1.2: Ones array (4×2)

In [36]:
ones_array = np.ones((4, 2))
print("Ones Array (4×2):")
print(ones_array)

Ones Array (4×2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## Task 1.3: np.full with fill value

In [37]:
full_array = np.full((3, 3), 5)
print("Full Array (filled with 5):")
print(full_array)

Full Array (filled with 5):
[[5 5 5]
 [5 5 5]
 [5 5 5]]


## Task 1.4: np.zeros_like

In [38]:
zeros_like_array = np.zeros_like(ones_array)
print("Zeros array (same shape as ones_array):")
print(zeros_like_array)

Zeros array (same shape as ones_array):
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


## Task 1.5: np.ones_like

In [39]:
ones_like_array = np.ones_like(ones_array)
print("Ones array (same shape as ones_array):")
print(ones_like_array)

Ones array (same shape as ones_array):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## Task 1.6: Convert list to NumPy array

In [40]:
my_list = [1, 2, 3, 4]
array_from_list = np.array(my_list)
print("Original list:", my_list)
print("NumPy array:")
print(array_from_list)

Original list: [1, 2, 3, 4]
NumPy array:
[1 2 3 4]


---
# PROBLEM 2: ARRAY MANIPULATION

## Task 2.1: Array from 10 to 49

In [41]:
array_10_49 = np.arange(10, 50)
print("Array from 10 to 49:")
print(array_10_49)

Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Task 2.2: 3×3 matrix (0-8) with reshape

In [42]:
matrix_0_8 = np.arange(9).reshape(3, 3)
print("3×3 matrix (0-8):")
print(matrix_0_8)

3×3 matrix (0-8):
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Task 2.3: 3×3 identity matrix

In [43]:
identity_matrix = np.eye(3)
print("3×3 Identity Matrix:")
print(identity_matrix)

3×3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Task 2.4: Random array (size 30) and its mean

In [44]:
random_array = np.random.rand(30)
print("Random array (first 10 elements):")
print(random_array[:10])
print(f"\nMean of the array: {random_array.mean():.4f}")

Random array (first 10 elements):
[0.78504598 0.56943743 0.20160087 0.42462463 0.06118568 0.77497149
 0.51288546 0.15876739 0.0367585  0.710715  ]

Mean of the array: 0.4548


## Task 2.5: 10×10 random array with min and max

In [45]:
random_matrix = np.random.rand(10, 10)
print("10×10 Random Matrix (first 5×5):")
print(random_matrix[:5, :5])
print(f"\nMin value: {random_matrix.min():.4f}")
print(f"Max value: {random_matrix.max():.4f}")

10×10 Random Matrix (first 5×5):
[[0.69233657 0.71384944 0.69840332 0.71819805 0.90773057]
 [0.00755962 0.08553609 0.19768246 0.43775277 0.96107041]
 [0.6647869  0.61820221 0.1072006  0.70999507 0.10832817]
 [0.68857275 0.77747831 0.66716528 0.44653827 0.80006795]
 [0.32656978 0.87515327 0.5276391  0.69752335 0.74079709]]

Min value: 0.0026
Max value: 0.9954


## Task 2.6: Zero array with 5th element = 1

In [46]:
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero array with 5th element = 1:")
print(zero_array)

Zero array with 5th element = 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Task 2.7: Reverse array

In [47]:
array_to_reverse = np.array([1, 2, 0, 0, 4, 0])
reversed_array = array_to_reverse[::-1]
print("Original array:")
print(array_to_reverse)
print("\nReversed array:")
print(reversed_array)

Original array:
[1 2 0 0 4 0]

Reversed array:
[0 4 0 0 2 1]


## Task 2.8: 2D array with border = 1, inside = 0

In [48]:
border_array = np.zeros((5, 5))
border_array[0, :] = 1
border_array[-1, :] = 1
border_array[:, 0] = 1
border_array[:, -1] = 1
print("5×5 array with border = 1, inside = 0:")
print(border_array)

5×5 array with border = 1, inside = 0:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Task 2.9: 8×8 Checkerboard pattern

In [49]:
checkerboard = np.zeros((8, 8))
checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1
print("8×8 Checkerboard pattern:")
print(checkerboard)

8×8 Checkerboard pattern:
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


---
# PROBLEM 3: ARRAY OPERATIONS

## Define arrays for Problem 3

In [50]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Array x:")
print(x)
print("\nArray y:")
print(y)
print("\nArray v:", v)
print("Array w:", w)

Array x:
[[1 2]
 [3 5]]

Array y:
[[5 6]
 [7 8]]

Array v: [ 9 10]
Array w: [11 12]


## Task 3.1: Add arrays x + y

In [51]:
result_add = x + y
print("x + y:")
print(result_add)

x + y:
[[ 6  8]
 [10 13]]


## Task 3.2: Subtract arrays x - y

In [52]:
result_subtract = x - y
print("x - y:")
print(result_subtract)

x - y:
[[-4 -4]
 [-4 -3]]


## Task 3.3: Multiply by integer

In [53]:
result_multiply = x * 2
print("x * 2:")
print(result_multiply)

x * 2:
[[ 2  4]
 [ 6 10]]


## Task 3.4: Square each element

In [54]:
result_square = x ** 2
print("x^2 (square each element):")
print(result_square)

x^2 (square each element):
[[ 1  4]
 [ 9 25]]


## Task 3.5: Dot products

In [55]:
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print("v · w (dot product):", dot_v_w)
print("\nx · v (dot product):", dot_x_v)
print("\nx · y (dot product):")
print(dot_x_y)

v · w (dot product): 219

x · v (dot product): [29 77]

x · y (dot product):
[[19 22]
 [50 58]]


In [56]:

concat_rows = np.concatenate([x, y], axis=0)
print("Concatenate x, y (rows):")
print(concat_rows)

concat_cols = np.column_stack([v, w])
print("\nConcatenate v, w (columns):")
print(concat_cols)

Concatenate x, y (rows):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v, w (columns):
[[ 9 11]
 [10 12]]


## Task 3.7: Try concatenating x and v (different shapes)

In [57]:
print("Trying to concatenate x and v (different shapes):")
print(f"x shape: {x.shape}")
print(f"v shape: {v.shape}")

try:
    result = np.concatenate([x, v])
    print(result)
except ValueError as e:
    print(f"\n ERROR: {e}")
    print("\n Explanation:")
    print("x has shape (2,2) and v has shape (2,).")
    print("They have different number of dimensions, so they cannot be")
    print("concatenated along axis=0.")
    print("\n Solution: Reshape v to (1,2) or use vstack instead.")
    result = np.vstack([x, v])
    print("\nUsing np.vstack:")
    print(result)

Trying to concatenate x and v (different shapes):
x shape: (2, 2)
v shape: (2,)

 ERROR: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

 Explanation:
x has shape (2,2) and v has shape (2,).
They have different number of dimensions, so they cannot be
concatenated along axis=0.

 Solution: Reshape v to (1,2) or use vstack instead.

Using np.vstack:
[[ 1  2]
 [ 3  5]
 [ 9 10]]


---
# PROBLEM 4: MATRIX OPERATIONS

## Define matrices for Problem 4

In [58]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

Matrix A:
[[3 4]
 [7 8]]

Matrix B:
[[5 3]
 [2 1]]


## Task 4.1: Prove A · A^(-1) = I

In [59]:
A_inverse = np.linalg.inv(A)
print("A^(-1) (inverse of A):")
print(A_inverse)

result = np.dot(A, A_inverse)
print("\nA · A^(-1):")
print(result)

print("\nIdentity Matrix (rounded):")
print(np.round(result))
print("\n A · A^(-1) = I (Identity Matrix)")

A^(-1) (inverse of A):
[[-2.    1.  ]
 [ 1.75 -0.75]]

A · A^(-1):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity Matrix (rounded):
[[1. 0.]
 [0. 1.]]

✅ A · A^(-1) = I (Identity Matrix)


AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB (A · B):")
print(AB)

print("\nBA (B · A):")
print(BA)

print("\nAB + BA:")
print(AB + BA)

print("\n📝 Note: AB ≠ BA, so matrix multiplication is NOT commutative!")

In [60]:
AB = np.dot(A, B)
AB_T = AB.T

print("(AB)^T (transpose of AB):")
print(AB_T)

B_T = B.T
A_T = A.T
B_T_A_T = np.dot(B_T, A_T)

print("\nB^T A^T:")
print(B_T_A_T)

are_equal = np.allclose(AB_T, B_T_A_T)
print(f"\n Are they equal? {are_equal}")
print("This proves: (AB)^T = B^T A^T")

(AB)^T (transpose of AB):
[[23 51]
 [13 29]]

B^T A^T:
[[23 51]
 [13 29]]

✅ Are they equal? True
This proves: (AB)^T = B^T A^T


## Task 4.3: Prove (AB)^T = B^T A^T

In [61]:
print("System of equations:")
print("3x + y - z = 9")
print("2x - 3y + z = -1")
print("x - y + 2z = -3")

coeff_matrix = np.array([[3, 1, -1],
                         [2, -3, 1],
                         [1, -1, 2]])

constants = np.array([9, -1, -3])

solution = np.linalg.solve(coeff_matrix, constants)

print("\nSolution:")
print(f"x = {solution[0]:.4f}")
print(f"y = {solution[1]:.4f}")
print(f"z = {solution[2]:.4f}")

print("\n Verification:")
eq1 = 3*solution[0] + solution[1] - solution[2]
eq2 = 2*solution[0] - 3*solution[1] + solution[2]
eq3 = solution[0] - solution[1] + 2*solution[2]
print(f"3x + y - z = {eq1:.4f} (should be 9)")
print(f"2x - 3y + z = {eq2:.4f} (should be -1)")
print(f"x - y + 2z = {eq3:.4f} (should be -3)")

System of equations:
3x + y - z = 9
2x - 3y + z = -1
x - y + 2z = -3

Solution:
x = 2.0000
y = 1.0000
z = -2.0000

 Verification:
3x + y - z = 9.0000 (should be 9)
2x - 3y + z = -1.0000 (should be -1)
x - y + 2z = -3.0000 (should be -3)


## Task 4.4: Solve system of equations

In [62]:
size = 1000000

print(f"Comparing Python lists vs NumPy for element-wise addition")
print(f"Size: {size:,}\n")

python_list_1 = list(range(size))
python_list_2 = list(range(size))

start = time.time()
python_add = [a + b for a, b in zip(python_list_1, python_list_2)]
python_time = time.time() - start

print(f"Python lists: {python_time:.6f} seconds")

numpy_array_1 = np.arange(size)
numpy_array_2 = np.arange(size)

start = time.time()
numpy_add = numpy_array_1 + numpy_array_2
numpy_time = time.time() - start

print(f"NumPy arrays: {numpy_time:.6f} seconds")
print(f"\n NumPy is {python_time / numpy_time:.2f}x FASTER!")

Comparing Python lists vs NumPy for element-wise addition
Size: 1,000,000

Python lists: 0.106463 seconds
NumPy arrays: 0.002472 seconds

 NumPy is 43.06x FASTER!


---
# EXPERIMENT: HOW FAST IS NUMPY?

## Experiment 1: Element-wise Addition

In [63]:
size = 1000000

print(f"Comparing Python lists vs NumPy for element-wise multiplication")
print(f"Size: {size:,}\n")

python_list_1 = list(range(size))
python_list_2 = list(range(size))

start = time.time()
python_mult = [a * b for a, b in zip(python_list_1, python_list_2)]
python_time = time.time() - start

print(f"Python lists: {python_time:.6f} seconds")

numpy_array_1 = np.arange(size)
numpy_array_2 = np.arange(size)

start = time.time()
numpy_mult = numpy_array_1 * numpy_array_2
numpy_time = time.time() - start

print(f"NumPy arrays: {numpy_time:.6f} seconds")
print(f"\n NumPy is {python_time / numpy_time:.2f}x FASTER!")

Comparing Python lists vs NumPy for element-wise multiplication
Size: 1,000,000

Python lists: 0.093676 seconds
NumPy arrays: 0.002247 seconds

 NumPy is 41.69x FASTER!


## Experiment 2: Element-wise Multiplication

In [64]:
size = 1000000

print(f"Comparing Python lists vs NumPy for dot product")
print(f"Size: {size:,}\n")

python_list_1 = list(range(size))
python_list_2 = list(range(size))

start = time.time()
python_dot = sum(a * b for a, b in zip(python_list_1, python_list_2))
python_time = time.time() - start

print(f"Python lists: {python_time:.6f} seconds")

numpy_array_1 = np.arange(size)
numpy_array_2 = np.arange(size)

start = time.time()
numpy_dot = np.dot(numpy_array_1, numpy_array_2)
numpy_time = time.time() - start

print(f"NumPy arrays: {numpy_time:.6f} seconds")
print(f"\n NumPy is {python_time / numpy_time:.2f}x FASTER!")

Comparing Python lists vs NumPy for dot product
Size: 1,000,000

Python lists: 0.090004 seconds
NumPy arrays: 0.001734 seconds

 NumPy is 51.90x FASTER!


## Experiment 3: Dot Product

In [32]:
size_matrix = 1000

print(f"Comparing Python lists vs NumPy for matrix multiplication")
print(f"Matrix size: {size_matrix}×{size_matrix}\n")

python_matrix_1 = [[i+j for j in range(size_matrix)] for i in range(size_matrix)]
python_matrix_2 = [[i+j for j in range(size_matrix)] for i in range(size_matrix)]

print("⏳ Computing Python lists (this may take a while)...")
start = time.time()
python_matmul = [[sum(python_matrix_1[i][k] * python_matrix_2[k][j]
                      for k in range(size_matrix))
                  for j in range(size_matrix)]
                 for i in range(size_matrix)]
python_time = time.time() - start

print(f"Python lists: {python_time:.6f} seconds")

numpy_matrix_1 = np.random.rand(size_matrix, size_matrix)
numpy_matrix_2 = np.random.rand(size_matrix, size_matrix)

print("⏳ Computing NumPy arrays...")
start = time.time()
numpy_matmul = np.dot(numpy_matrix_1, numpy_matrix_2)
numpy_time = time.time() - start

print(f"NumPy arrays: {numpy_time:.6f} seconds")
print(f"\n NumPy is {python_time / numpy_time:.2f}x FASTER!")
print("\n This is why NumPy is so important for data science!")

Comparing Python lists vs NumPy for matrix multiplication
Matrix size: 1000×1000

⏳ Computing Python lists (this may take a while)...
Python lists: 257.287831 seconds
⏳ Computing NumPy arrays...
NumPy arrays: 0.064247 seconds

🚀 NumPy is 4004.69x FASTER!

💡 This is why NumPy is so important for data science!


## Experiment 4: Matrix Multiplication (1000×1000)

In [33]:
# Compare Python lists vs NumPy for matrix multiplication
size_matrix = 1000

print(f"Comparing Python lists vs NumPy for matrix multiplication")
print(f"Matrix size: {size_matrix}×{size_matrix}\n")

# Python lists (nested)
python_matrix_1 = [[i+j for j in range(size_matrix)] for i in range(size_matrix)]
python_matrix_2 = [[i+j for j in range(size_matrix)] for i in range(size_matrix)]

print("⏳ Computing Python lists (this may take a while)...")
start = time.time()
python_matmul = [[sum(python_matrix_1[i][k] * python_matrix_2[k][j]
                      for k in range(size_matrix))
                  for j in range(size_matrix)]
                 for i in range(size_matrix)]
python_time = time.time() - start

print(f"Python lists: {python_time:.6f} seconds")

# NumPy arrays
numpy_matrix_1 = np.random.rand(size_matrix, size_matrix)
numpy_matrix_2 = np.random.rand(size_matrix, size_matrix)

print("⏳ Computing NumPy arrays...")
start = time.time()
numpy_matmul = np.dot(numpy_matrix_1, numpy_matrix_2)
numpy_time = time.time() - start

print(f"NumPy arrays: {numpy_time:.6f} seconds")
print(f"\n NumPy is {python_time / numpy_time:.2f}x FASTER!")
print("\n This is why NumPy is so important for data science!")

Comparing Python lists vs NumPy for matrix multiplication
Matrix size: 1000×1000

⏳ Computing Python lists (this may take a while)...
Python lists: 187.898119 seconds
⏳ Computing NumPy arrays...
NumPy arrays: 0.058035 seconds

🚀 NumPy is 3237.66x FASTER!

💡 This is why NumPy is so important for data science!
